### ISSUE TITLE
Github Clasroom

### ISSUE THREAD

**Issue by juanpflores** [gwolf/sistop-2017-2#73]
Hey @gwolf,
Github sacó hace algún tiempo un conjunto de herramientas para organizar entregas de tareas y código de clases llamada [Github Classroom](https://classroom.github.com/#) podría ser bueno revisarlo y ver si puede hacer más sencillo la entrega de proyectos para tu clase. 

Saludos!

**Comment by gwolf** [comment]
¡Gracias!
Estoy al tanto de estas herramientas, aunque no he entrado a revisarlas como quisiera, por falta de tiempo. Espero poder hacerlo en el descanso entre este semestre y el otro.
¡Un saludo, y mucho gusto en leerte nuevamente!
